[profile.ci.fuzz]
runs = 10_000

[profile.default]
src = 'src'
test = 'test'
script = 'script'
remappings = []
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 500
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000

[rpc_endpoints]
westend_asset_hub = "https://westend-asset-hub-eth-rpc.polkadot.io"

[etherscan]
